// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7kn4MVEeyl9sOpFJ3orZTAsSV8Hxwdb8',
    appId: '1:388815033509:web:3e75dfc608fcb52ed0a94c',
    messagingSenderId: '388815033509',
    projectId: 'first-18d1a',
    authDomain: 'first-18d1a.firebaseapp.com',
    storageBucket: 'first-18d1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeduhROoDQ5UrK6ajBuypibut9f2R-fOg',
    appId: '1:388815033509:android:286ab0c576b69587d0a94c',
    messagingSenderId: '388815033509',
    projectId: 'first-18d1a',
    storageBucket: 'first-18d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5vWafhLWa4IZVCUazI7dYvMdNXvD-fnA',
    appId: '1:388815033509:ios:d90515645dbd2a74d0a94c',
    messagingSenderId: '388815033509',
    projectId: 'first-18d1a',
    storageBucket: 'first-18d1a.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5vWafhLWa4IZVCUazI7dYvMdNXvD-fnA',
    appId: '1:388815033509:ios:4b7122b32e49e8eed0a94c',
    messagingSenderId: '388815033509',
    projectId: 'first-18d1a',
    storageBucket: 'first-18d1a.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
